# use an official Python runtime as a parent image
FROM python:3.9-slim

# set the working directory in the container
WORKDIR /app

# copy the requirements file first to leverage Docker cache
COPY requirements.txt .

# install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# copy the requirements file first to leverage Docker cache
COPY requirements.txt .

# copy the current directory contents into the container at /app
COPY . .

# make port 8000 available to the world outside this container
EXPOSE 8000

# run app.py when the container launches
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
